// servicesData.js
// Dati separati per facilitare la modifica da parte degli sposi

const servicesData = [
  // ─── Bellezza ───
  {
    id: 1,
    category: 'beauty',
    categoryLabel: 'Parrucchieri',
    emoji: '💇',
    name: 'Luxury Experience',
    detail: 'Via Teano 10, Rosarno RC\nSpecializzato in acconciature da cerimonia. Aperto il sabato.',
    phone: '+39 0966774704',
    maps: 'https://share.google/fpoOzX3dC2UnkqREL',
  },
  {
    id: 2,
    category: 'beauty',
    categoryLabel: 'Make-up',
    emoji: '💄',
    name: 'Giulia Ferraro MUA',
    detail: 'Nicotera VV — Freelance\nDisponibile per location. Booking consigliato con 3 mesi di anticipo.',
    phone: '+39 340 000 1111',
    maps: null,
  },
  {
    id: 3,
    category: 'beauty',
    categoryLabel: 'Parrucchieri',
    emoji: '✂️',
    name: 'Atelier Capelli Lidia',
    detail: 'Corso Umberto 45, Nicotera VV\nAcronciature da sposa e cerimonia. Prezzi su richiesta.',
    phone: '+39 096 501 5678',
    maps: 'https://maps.google.com/?q=Nicotera+VV',
  },

  // ─── Trasporti ───
  {
    id: 4,
    category: 'trasporti',
    categoryLabel: 'Noleggio auto',
    emoji: '🚗',
    name: 'Rent & Go Lamezia',
    detail: 'Aeroporto di Lamezia Terme\nNoleggio auto dal più vicino aeroporto. Prenotazione online consigliata.',
    phone: null,
    maps: 'https://maps.google.com/?q=Aeroporto+Lamezia+Terme',
    url: 'https://www.rentalcars.com',
  },
  {
    id: 5,
    category: 'trasporti',
    categoryLabel: 'Taxi / NCC',
    emoji: '🚕',
    name: 'NCC Calabria Sud',
    detail: 'Servizio da/per aeroporti e stazioni.\nPrenotazione telefonica — prezzi fissi e concordati.',
    phone: '+39 350 000 2222',
    maps: null,
  },
  {
    id: 6,
    category: 'trasporti',
    categoryLabel: 'Taxi / NCC',
    emoji: '🚕',
    name: 'Taxi Rosarno',
    detail: 'Servizio taxi locale disponibile 24h.\nIndicato per spostamenti tra chiesa e ricevimento.',
    phone: '+39 096 500 9999',
    maps: null,
  },

  // ─── Hotel ───
  {
    id: 7,
    category: 'hotel',
    categoryLabel: 'Hotel',
    emoji: '🏨',
    name: 'Hotel Marinara',
    detail: 'Via Marina 1, Nicotera Marina VV\nFronte mare. Camere con vista. Convenzione sposi disponibile.',
    phone: '+39 096 579 0001',
    maps: 'https://maps.google.com/?q=Nicotera+Marina+VV',
  },
  {
    id: 8,
    category: 'hotel',
    categoryLabel: 'B&B',
    emoji: '🏡',
    name: 'B&B Sole e Vento',
    detail: 'Nicotera Alta VV\nVista sul golfo. Colazione inclusa. Gestione familiare.',
    phone: '+39 320 000 3333',
    maps: 'https://maps.google.com/?q=Nicotera+VV',
  },
  {
    id: 9,
    category: 'hotel',
    categoryLabel: 'Agriturismo',
    emoji: '🌾',
    name: 'Agriturismo Torre Vecchia',
    detail: 'SP 60, Rosarno RC\nCamere rustiche con piscina. Colazione con prodotti locali. Ideale per famiglie.',
    phone: '+39 096 500 4444',
    maps: 'https://maps.google.com/?q=Rosarno+RC',
  },

  // ─── Aeroporti ───
  {
    id: 10,
    category: 'aeroporti',
    categoryLabel: 'Aeroporti',
    emoji: '✈️',
    name: 'Aeroporto Lamezia Terme',
    detail: 'Lamezia Terme CZ — Codice: SUF\nDistanza: ~80 km. Collegato con principali città italiane.',
    phone: '+39 096 800 0000',
    maps: 'https://maps.google.com/?q=Aeroporto+Lamezia+Terme',
    url: 'https://sacal.it',
  },
  {
    id: 11,
    category: 'aeroporti',
    categoryLabel: 'Aeroporti',
    emoji: '✈️',
    name: 'Aeroporto Reggio Calabria',
    detail: 'Reggio Calabria RC — Codice: REG\nDistanza: ~70 km. Voli da Roma, Milano e altre città.',
    phone: '+39 096 540 0000',
    maps: 'https://maps.google.com/?q=Aeroporto+Reggio+Calabria',
    url: 'https://www.aeroporto.rc.it',
  },
];
